default: call_f

all: make_f call_f
	@echo blaaa

make_f:
	cd ~/ver84/exe/file; make -j8 # change this directory to use diffenrent feap including diffenrent user element
	@echo make_f

call_f:
	~/ver84/exe/file/feap -iIcap # change this directory to use diffenrent feap including diffenrent user element
	@echo call_f